---
- name: Prepare servers for Jenkins
  hosts: servers
  become: true

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin  # This is Docker Compose v2
        state: latest
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Java 17 (OpenJDK)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Verify Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    - name: Verify Java version
      command: java -version
      register: java_version
      changed_when: false
      ignore_errors: true

    - name: Print Java version
      debug:
        msg: "{{ java_version.stderr_lines }}"
